<?php
require"config.php"

// Create connection
$con=mysqli_connect(HOST,USER,PASS,DB);

// Check connection
if (mysqli_connect_errno($con))
  {
  echo "Failed to connect to MySQL: " . mysqli_connect_error();
  }




//run the query
$result = mysqli_query($con,"select users.firstname, users.lastname, users.username, role.role_name, service.am_pm from users,role,rota,service where (role.role_name = 'Service Leader' or role.role_name = 'Worship Leader' or role.role_name = 'Speaker') and role.idrole = rota.role_idrole and users.id = rota.users_id and  service.idservice = rota.service_idservice
 and service.date < ADDDATE(NOW(), Interval 7 Day) and DAYOFWEEK(service.date) >= 1 and service.date > NOW() order by service.am_pm asc");

$rota .= "<table border='1' cellpadding='3' cellspacing='0' width='100%' class='table table-striped table-bordered table-condensed table-hover'>";



//loop through the results to contruct the rota - Who's doing what
while($row = mysqli_fetch_array($result))
  {
  	
  	$rota .= "<tr>";
  $rota .= "<td> " . $row['am_pm'] . "</td><td>" . $row['role_name'] . "</td><td><a href=mailto:" . $row['username'] . ">" . $row['firstname'] . "</a></td></tr>";
  
  }
$rota .= "</table>";



//extract email addresses to send it.
$result2 = mysqli_query($con,"select users.username,users.firstname, users.lastname, role.role_name, service.am_pm from users,role,rota,service where (role.role_name = 'Service Leader' or role.role_name = 'Worship Leader' or role.role_name = 'Speaker') and role.idrole = rota.role_idrole and users.id = rota.users_id and  service.idservice = rota.service_idservice
 and service.date < ADDDATE(NOW(), Interval 7 Day) and DAYOFWEEK(service.date) >= 1 and service.date > NOW() order by service.am_pm asc ");
 
 while($row2 = mysqli_fetch_array($result2)){
 	$to = null;
	$text = null;
	$message = null;


//construct the email
 	$text .= "Hi " . $row2['firstname'] . ",<br>";
 	$text .= "You are receiving this email as you are involved in one of the services at CFM this coming Sunday. Please find below a list of who is involved this Sunday.<br><br>";
 	
 	$text .= $rota;
 	
 	$text .= "<br><hr>";
 	$text .= "<p><small>This email was automatically generated by www.cfmworship.org.uk.</small></p>";
 	
 	$message = $text;
 	 	
 	$headers .= 'From: <songlist@cfmworship.org.uk>' . "\r\n";
    $headers .= "MIME-Version: 1.0\r\n";
    $headers .= "Content-Type: text/html; charset=ISO-8859-1\r\n";
	$subject = "This Sunday";
 
//get the recpients
 	$to = $row2['username'];
 	



 //send the email
 
mail($to,$subject,$message,$headers); 
 #echo "$to <br><hr>";
 #echo "$subject <br><hr>";
 #echo "$message <br><hr>";




	
 }
 
//construct the message and send the email 

 










//close the connection
mysqli_close($con);


?>
